# Generated by Django 4.0.3 on 2022-07-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='image/')),
                ('name', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.TextField(max_length=50)),
            ],
        ),
    ]
